version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: task-planner-laravel
        container_name: task-planner-laravel
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
        ports:
            - "9000:9000"
        networks:
            - laravel

    webserver:
        image: nginx:alpine
        container_name: nginx
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - .:/var/www
            - ./nginx:/etc/nginx/conf.d
        networks:
            - laravel

networks:
    laravel:
        driver: bridge
